import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import IndexNavBar from "@/components/NavBars/IndexNavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <IndexNavBar child={children} />
      </body>
    </html>
  );
}
